site_name: "Documentación Técnica DWES"
site_description: "Guía de estándares, arquitectura web y servidor para DAW"
site_author: "Alumno DAW - IES Los Albares"

# Selección del tema Read the Docs
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - php
    - bash
    - json
    - html

# Estructura de navegación lateral
nav:
  - Inicio: index.php.md
  - Estándares y Nombrado:
      - Reglas de Directorios: estandares/nombrado.md
  - Servidor Web:
      - Protocolo HTTP: servidor/respuestas-http.md

# Opciones adicionales
markdown_extensions:
  - tables
  - codehilite

